version: '3'

services: 
    api:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/usr/src/app
        ports:
            - 8081:8081
        working_dir: /usr/src/app